POST http://localhost:4009/api/greet
 content-type: application/json

{
    "language": "Xhosa",
    "greeting": "Molo"
}
###
POST http://localhost:4009/api/greet
 content-type: application/json

{
    "language": "Zulu",
    "greeting": "Sawubona"
}