POST https://greeting-api.onrender.com/api/greet
 content-type: application/json

{
    "language": "Xhosa",
    "greeting": "Molo"
}
###
POST https://greeting-api.onrender.com/api/greet
 content-type: application/json

{
    "language": "Zulu",
    "greeting": "Sawubona"
}